version: '3'

services:
  attic:
    restart: unless-stopped
    image: ghcr.io/pschmitt/attic:latest
    ports:
      - "8080:8080"
    # environment:
    # - "ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64=CHANGE-ME"
    volumes:
      # - ./config:/config
      - ./data:/data
